server:
  context-path: /
  port: 7008

#zipkin:
#  storage:
#    type: mysql
spring:
  sleuth:
    enabled: false
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://10.10.110.218:3306/test_xx?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      schema[0]: classpath:/zipkin.sql
  jpa:
      hibernate:
          ddl-auto: update
