server:
    context-path: /configServer
    port: 7000

spring:
    application:
        name: configServer
    cloud:
        config:
            server:
                database: true
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update