server:
  context-path: /provider
  port: 7003

spring:
  application:
    name: provider
  cloud:
      config:
        name: provider
        profile: dev
        label: master
        uri: http://localhost:7000/configServer

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7002/eureka/
