server:
  context-path: /provider
  port: 7005

spring:
  application:
    name: provider
  #config server配置
  cloud:
      config:
        name: provider
        profile: dev
        label: master
        uri: http://10.10.5.185:7000/configServer

eureka:
  instance:
     #配置访问client的host
     hostname: ${spring.cloud.client.ipAddress}
     #配置显示ip:port
     instance-id: ${spring.cloud.client.ipAddress}:${server.port}
     prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.10.5.185:7002/eureka/
